from fpdf import FPDF
import os
import json
import logging
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class ClinicalIntegrityReport(FPDF):
    def header(self):
        self.set_fill_color(15, 23, 42) # Dark Slate
        self.rect(0, 0, 210, 30, 'F')
        self.set_font('helvetica', 'B', 18)
        self.set_text_color(255, 255, 255)
        self.cell(0, 20, 'MEDICAL DATA INTEGRITY & PROGRESSION REPORT', border=0, new_x="LMARGIN", new_y="NEXT", align='C')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Auto-ETL Intelligence Suite', 0, 0, 'C')

def generate_pdf_report(stats_path: str, cleaned_path: str, output_path: str):
    """
    Generate professional Clinical Integrity Briefing.
    """
    try:
        if not os.path.exists(stats_path) or not os.path.exists(cleaned_path):
            logging.error("Required data files for reporting not found.")
            return

        with open(stats_path, "r") as f:
            stats = json.load(f)

        # 1. Generate Visuals
        sns.set_theme(style="whitegrid")
        df = pd.read_csv(cleaned_path)
        df['date'] = pd.to_datetime(df['date'])
        
        os.makedirs("temp_plots", exist_ok=True)
        
        # Plot: Global progression
        plt.figure(figsize=(10, 5))
        global_trend = df.groupby('date')['total_cases'].sum().dropna()
        plt.plot(global_trend.index, global_trend.values, color='#38bdf8', linewidth=2.5)
        plt.fill_between(global_trend.index, global_trend.values, color='#38bdf8', alpha=0.1)
        plt.title('Global Caseload Progression (Validated Vector)', fontsize=14, pad=20)
        plt.xlabel('Timeline', fontsize=12)
        plt.ylabel('Cumulative Totals', fontsize=12)
        plt.tight_layout()
        plt.savefig('temp_plots/progression.png', dpi=300)
        plt.close()

        # 2. PDF Compilation
        pdf = ClinicalIntegrityReport()
        pdf.add_page()
        pdf.set_font("helvetica", size=11)

        # Execution Summary
        pdf.set_font("helvetica", 'B', 14)
        pdf.set_text_color(2, 132, 199) # Blue
        pdf.cell(0, 10, "1. Executive Summary", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", '', 11)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)
        pdf.multi_cell(0, 7, f"Analysis executed at {datetime.now().strftime('%Y-%m-%d %H:%M')}. This report certifies the clinical integrity of the dataset after automated intervention.")
        pdf.ln(5)

        # Integrity Statistics Table
        pdf.set_font("helvetica", 'B', 13)
        pdf.cell(0, 10, "2. Data Transformation Statistics", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", '', 11)
        
        pdf.set_fill_color(241, 245, 249)
        pdf.cell(100, 10, "Integrity Metric", border=1, fill=True)
        pdf.cell(0, 10, "Result / Value", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

        metrics = [
            ("Initial Records Ingested", format(stats.get('initial_rows', 0), ',')),
            ("Final Processed Records", format(stats.get('final_rows', 0), ',')),
            ("Monotonicity Repaired", str(stats.get('monotonicity_repairs', 0))),
            ("Outliers Redistributed", str(stats.get('outliers_redistributed', 0))),
            ("Clinical Features Detected", str(stats.get('features', 0)))
        ]

        for m_name, m_val in metrics:
            pdf.cell(100, 10, m_name, border=1)
            pdf.cell(0, 10, m_val, border=1, new_x="LMARGIN", new_y="NEXT")
        
        pdf.ln(10)

        # Audit Log Section
        pdf.set_font("helvetica", 'B', 13)
        pdf.set_text_color(2, 132, 199)
        pdf.cell(0, 10, "3. Detailed Step-by-Step Audit Log", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("helvetica", '', 11)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(2)
        
        for step in stats.get('audit_steps', []):
            pdf.multi_cell(0, 8, f"- {step}", border='L')
            pdf.ln(1)
            
        pdf.add_page()
        # Visual Progression
        pdf.set_font("helvetica", 'B', 13)
        pdf.set_text_color(2, 132, 199)
        pdf.cell(0, 10, "4. Global Progression Visualization", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
        pdf.image('temp_plots/progression.png', x=10, w=190)

        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        pdf.output(output_path)
        logging.info(f"Professional Integrity Briefing generated at {output_path}")

        # Cleanup
        if os.path.exists('temp_plots/progression.png'): os.remove('temp_plots/progression.png')
        if os.path.exists('temp_plots'): os.rmdir('temp_plots')

    except Exception as e:
        logging.error(f"Reporting failure: {e}")
